server:
  port: 8080
info: Welcome to iUAP exams v5.0!  @CopyRight 用友网络科技股份有限公司
logging:
  path: ./logs
  file:  iuap-exams.log
  level:
    root: debug

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
