server:
  port: 8080
info: Welcome to iUAP exams v5.0!  @CopyRight 用友网络科技股份有限公司
logging:
  path: ./logs
  file:  iuap-exams.log
  level:
    root: debug

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    #static-path-pattern: /static/**
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
